DROP TABLE IF EXISTS citas;
DROP TABLE IF EXISTS pacientes;
DROP TABLE IF EXISTS doctores;

CREATE TABLE pacientes (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nombre VARCHAR(100) NOT NULL,
                           telefono VARCHAR(30)
);

CREATE TABLE doctores (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre VARCHAR(100) NOT NULL,
                          especialidad VARCHAR(100) NOT NULL
);

CREATE TABLE citas (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       paciente_id BIGINT NOT NULL,
                       doctor_id BIGINT NOT NULL,
                       fecha DATE NOT NULL,
                       estado VARCHAR(30) NOT NULL,
                       CONSTRAINT fk_cita_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes(id),
                       CONSTRAINT fk_cita_doctor FOREIGN KEY (doctor_id) REFERENCES doctores(id)
);